### ISSUE TITLE
No suggestions for e.msg to get the error message

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/plugin-intellij#457] opened 2017-06-29 08:26 UTC
eg:

```
catch (errors:Error e) {
            system:println("Error"+ e.msg);
            messages:setStringPayload(msg, e.msg);
        }
```

**Comment by Shan1024** [comment] 2017-06-29 18:53
Duplicate of https://github.com/ballerinalang/plugin-intellij/issues/383.

**Closed** 2017-07-20 16:43 UTC
Labels: bug, duplicate
