### ISSUE TITLE
Suggestions are not working inside the transform block

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/plugin-intellij#372] opened 2017-06-07 09:04 UTC
transform {
        e.fname = p.first_name;
        e.lname = p.last_name;
        e.age = p.age;
 }

**Comment by Shan1024** [comment] 2017-06-07 09:34
Duplicate of https://github.com/ballerinalang/plugin-intellij/issues/370. PR already sent - https://github.com/ballerinalang/plugin-intellij/pull/371.

**Closed by Shan1024** 2017-06-07 09:34 UTC
Labels: duplicate
