### ISSUE TITLE
No auto completion available for `function`

### ISSUE THREAD

**Issue by dilini-muthumala** [ballerinalang/plugin-intellij#642] opened 2017-10-13 10:05 UTC
![auto_completion_func](https://user-images.githubusercontent.com/7592890/31541397-208bde78-b02c-11e7-81ef-8113bf94809f.png)

**Comment by Shan1024** [comment] 2017-10-13 11:50
Hi @dilini-muthumala,

What is the plugin version you are using?

**Comment by dilini-muthumala** [comment] 2017-10-16 05:44
Hi @Shan1024 , I am using plugin version 0.9.1

**Comment by Shan1024** [comment] 2017-10-16 05:51
Hi @dilini-muthumala,

I could not reproduce this issue. Would you be able to provide a sample code where the auto completion is not working properly?

**Comment by dilini-muthumala** [comment] 2017-10-16 09:03
Hi @Shan1024 ,

Please find the screenshot below:

![no-autocompletion](https://user-images.githubusercontent.com/7592890/31603758-c793008a-b27e-11e7-8efb-3bb0c5a07ea6.png)

Program is:
```
import ballerina.lang.system;

function main (string[] args) {
    system:println("test!");
}
```

when I type 'func', it does not give any suggestions.

**Comment by Shan1024** [comment] 2017-12-13 09:07
Closing since cannot reproduce.

**Closed by Shan1024** 2017-12-13 09:07 UTC
Labels: Resolution/Cannot Reproduce
