### ISSUE TITLE
Package import suggestions not working

### ISSUE THREAD

**Issue by pubudu91** [ballerinalang/plugin-intellij#482] opened 2017-07-19 05:26 UTC
When moving the cursor to a package name we haven't imported (i.e: 'files' in the code snippet given below) and pressing Alt+Enter, it doesn't give us a list of suggested packages to import. 

```
files:File target = {path: "ftp://127.0.0.1/public/userB/mv.txt"};
```

**Comment by Shan1024** [comment] 2017-07-19 08:55
@pubudu91 : Is the module is a Ballerina module and is there any syntax highlighting error(anywhere in the file) present at that moment?

**Comment by Shan1024** [comment] 2017-11-17 06:21
Closing the issue since cannot reproduce.

**Comment by Shan1024** [comment] 2017-11-17 06:22
Closing the issue since cannot reproduce.

**Closed by Shan1024** 2017-11-17 06:22 UTC
Labels: Resolution/Cannot Reproduce
