### ISSUE TITLE
The map variable does not auto populate inside the join block

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/plugin-intellij#455] opened 2017-06-27 08:05 UTC
The map variable (joinMsg in this example) does not auto populate inside the join block

```
join (all) (map joinMsg) {
          messages:setStringPayload(result, joinMsg);
}
```

**Comment by Shan1024** [comment] 2017-06-28 07:00
Duplicate of https://github.com/ballerinalang/plugin-intellij/issues/399.

**Comment by Shan1024** [comment] 2017-08-10 08:23
Fixed in https://github.com/ballerinalang/plugin-intellij/pull/469.

**Closed by Shan1024** 2017-08-10 08:23 UTC
Labels: bug, duplicate
