### ISSUE TITLE
[Team VCoDeS]: Couldn't create a connector file

### ISSUE THREAD

**Issue by hbsviduranga** [ballerinalang/plugin-intellij#518] opened 2017-07-22 07:12 UTC
#@![connector1](https://user-images.githubusercontent.com/1680709/28489210-1906626e-6edb-11e7-90a7-cf334ce6749f.PNG)
![connector_error](https://user-images.githubusercontent.com/1680709/28489212-20c0961e-6edb-11e7-8a1f-b868be19c5b6.PNG)

**Comment by Shan1024** [comment] 2017-07-22 09:50
Duplicate of #517

**Closed** 2017-07-26 04:51 UTC
Labels: duplicate
