### ISSUE TITLE
[Package] Package import not resolved

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/plugin-intellij#702] opened 2017-11-09 07:07 UTC
As shown in attached image, the package import not resolved

![idea_2](https://user-images.githubusercontent.com/15624590/32592626-aa76055e-c54a-11e7-97a3-fadfffbdbdcd.png)

**Comment by Shan1024** [comment] 2017-11-10 10:08
Hi @erandidesilva,

This project is not a Ballerina project and hence the Ballerina support is very minimum. Can you check whether this issue exist in a Ballerina project as well?

**Comment by Shan1024** [comment] 2017-11-17 06:24
Closing the issue since this is issue cannot be reproduced in Ballerina projects.

**Closed by Shan1024** 2017-11-17 06:24 UTC
Labels: Type/Bug
