### ISSUE TITLE
Unresolved references: delay and interval

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/plugin-intellij#704] opened 2017-11-10 11:50 UTC
![81](https://user-images.githubusercontent.com/1845370/32657323-525fc354-c63b-11e7-9ba8-3750e99c710d.png)

**Comment by Shan1024** [comment] 2017-11-10 11:52
Duplicate of https://github.com/ballerinalang/plugin-intellij/issues/688.

**Closed** 2017-11-20 09:31 UTC
Labels: Resolution/Duplicate
