### ISSUE TITLE
Connector template contains old syntax

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/plugin-intellij#711] opened 2017-11-17 07:40 UTC
Please see below image

![issue_1](https://user-images.githubusercontent.com/15624590/32936062-b8b3657c-cb98-11e7-85d8-d68518a96cb5.png)

**Comment by Shan1024** [comment] 2017-11-20 09:31
Duplicate of https://github.com/ballerinalang/plugin-intellij/issues/709.

**Closed by Shan1024** 2017-11-20 09:31 UTC
Labels: Resolution/Duplicate
